name: RL_GR
dependencies:
  - python=3.7
  - matplotlib
  - numpy
  - scipy
  - basemap
  - pandas
  - pillow
  - keras
  - tensorflow=1.14
  - pip:
    - gym==0.12.1
    - torch --find-links https://download.pytorch.org/whl/cpu

